# Instalação e importação das bibliotecas

In [1]:
# Bibliotecas necessárias
import pandas as pd
import sqlalchemy

In [2]:
# Definindo a quantidade máxima de colunas a serem exibidas na visualização do dataframe
pd.set_option('display.max_columns',100)

# ETL (Extract, Transform, and Load)

## Extract

In [3]:
# Lendo o arquivo XLSX (Excel) através do Pandas e criando o dataframe com os dados do arquivo
df = pd.read_excel('https://www.camara.leg.br/cotas/Ano-2025.xlsx')

df

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
0,LID.GOV-CD,NaN,NaN,NaN,2023,NaN,NaN,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,1984,0,2025-02-07T00:00:00,1467.0,0.0,1467.0,2,2025,0,NaN,NaN,2115566,NaN,NaN,NaN,2812,7877589,https://www.camara.leg.br/cota-parlamentar/doc...
1,LID.GOV-CD,NaN,NaN,NaN,2023,NaN,NaN,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,2060,0,2025-03-11T00:00:00,1467.0,0.0,1467.0,3,2025,0,NaN,NaN,2123760,NaN,NaN,NaN,2812,7892756,https://www.camara.leg.br/cota-parlamentar/doc...
2,LID.GOV-CD,NaN,NaN,NaN,2023,NaN,NaN,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,2143,0,2025-04-11T00:00:00,1467.0,0.0,1467.0,4,2025,0,NaN,NaN,2131750,NaN,NaN,NaN,2812,7907982,https://www.camara.leg.br/cota-parlamentar/doc...
3,LID.GOV-CD,NaN,NaN,NaN,2023,NaN,NaN,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,2219,0,2025-05-12T00:00:00,1467.0,0.0,1467.0,5,2025,0,NaN,NaN,2139804,NaN,NaN,NaN,2812,7923034,https://www.camara.leg.br/cota-parlamentar/doc...
4,LID.GOV-CD,NaN,NaN,NaN,2023,NaN,NaN,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,2298,0,2025-06-03T00:00:00,1467.0,0.0,1467.0,6,2025,0,NaN,NaN,2150181,NaN,NaN,NaN,2812,7940865,https://www.camara.leg.br/cota-parlamentar/doc...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207570,Vanderlan Alves,2.964896e+09,234673.0,632.0,2023,CE,REPUBLICANOS,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,TAMIRES MEDEIROS SALES,519.967.580/0016-2,30,0,2025-12-26T00:00:00,4150.0,0.0,4150.0,12,2025,0,NaN,NaN,2199991,NaN,NaN,NaN,3803,8034979,https://www.camara.leg.br/cota-parlamentar/doc...
207571,Vanderlan Alves,2.964896e+09,234673.0,632.0,2023,CE,REPUBLICANOS,57,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,0,NaN,50.340.443 LAISY OLIVEIRA COSTA DE LIMA,503.404.430/0010-8,13421,4,2025-12-18T00:00:00,80.0,0.0,80.0,12,2025,0,NaN,NaN,2198808,NaN,NaN,NaN,3803,8032796,https://www.camara.leg.br/cota-parlamentar/not...
207572,Vanderlan Alves,2.964896e+09,234673.0,632.0,2023,CE,REPUBLICANOS,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,NaN,EM LOCACAO E COMERCIO DE VEICULOS LTDA,545.802.440/0020-9,18,4,2025-12-22T00:00:00,10400.0,0.0,10400.0,12,2025,0,NaN,NaN,2199423,NaN,NaN,NaN,3803,8033995,https://www.camara.leg.br/cota-parlamentar/not...
207573,Heloísa Helena,3.645032e+10,234788.0,633.0,2023,RJ,REDE,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,EDVALDO FRANCISCO DE OLIVEIRA 49191160120,323.738.120/0017-9,257,4,2025-12-19T00:00:00,194.4,0.0,194.4,12,2025,0,NaN,NaN,2206738,NaN,NaN,NaN,3804,8046527,https://www.camara.leg.br/cota-parlamentar/not...
207574,Heloísa Helena,3.645032e+10,234788.0,633.0,2023,RJ,REDE,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,MIL E UMA IDEIAS CONSULTORIA EM MARKETING E CO...,366.781.610/0018-6,188,0,2026-02-02T00:00:00,15000.0,0.0,15000.0,12,2025,0,NaN,NaN,2205674,NaN,NaN,NaN,3804,8044458,https://www.camara.leg.br/cota-parlamentar/doc...

In [4]:
# # Verificando os 3 últimos registros do dataframe
df.tail(3)

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
207572,Vanderlan Alves,2.964896e+09,234673.0,632.0,2023,CE,REPUBLICANOS,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,NaN,EM LOCACAO E COMERCIO DE VEICULOS LTDA,545.802.440/0020-9,18,4,2025-12-22T00:00:00,10400.0,0.0,10400.0,12,2025,0,NaN,NaN,2199423,NaN,NaN,NaN,3803,8033995,https://www.camara.leg.br/cota-parlamentar/not...
207573,Heloísa Helena,3.645032e+10,234788.0,633.0,2023,RJ,REDE,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,EDVALDO FRANCISCO DE OLIVEIRA 49191160120,323.738.120/0017-9,257,4,2025-12-19T00:00:00,194.4,0.0,194.4,12,2025,0,NaN,NaN,2206738,NaN,NaN,NaN,3804,8046527,https://www.camara.leg.br/cota-parlamentar/not...
207574,Heloísa Helena,3.645032e+10,234788.0,633.0,2023,RJ,REDE,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,MIL E UMA IDEIAS CONSULTORIA EM MARKETING E CO...,366.781.610/0018-6,188,0,2026-02-02T00:00:00,15000.0,0.0,15000.0,12,2025,0,NaN,NaN,2205674,NaN,NaN,NaN,3804,8044458,https://www.camara.leg.br/cota-parlamentar/doc...

## Transform

### 1. Investigando os dados do dataframe

In [5]:
# Exibindo os número de linhas e colunas do dataframe
df.shape

(207575, 32)

In [6]:
# Exibindo informações resumidas do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207575 entries, 0 to 207574
Data columns (total 32 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   txNomeParlamentar          207575 non-null  object
 1   cpf                        206639 non-null  float64
 2   ideCadastro                206639 non-null  float64
 3   nuCarteiraParlamentar      206639 non-null  float64
 4   nuLegislatura              207575 non-null  int64
 5   sgUF                       206639 non-null  object
 6   sgPartido                  206639 non-null  object
 7   codLegislatura             207575 non-null  int64
 8   numSubCota                 207575 non-null  int64
 9   txtDescricao               207575 non-null  object
 10  numEspecificacaoSubCota    207575 non-null  int64
 11  txtDescricaoEspecificacao  71467 non-null   object
 12  txtFornecedor              207575 non-null  object
 13  txtCNPJCPF                 170996 non-null  object
 14  txtNumero                  207575 non-null  object
 15  indTipoDocumento           207575 non-null  int64
 16  datEmissao                 199741 non-null  object
 17  vlrDocumento               207575 non-null  float64
 18  vlrGlosa                   207575 non-null  float64
 19  vlrLiquido                 207575 non-null  float64
 20  numMes                     207575 non-null  int64
 21  numAno                     207575 non-null  int64
 22  numParcela                 207575 non-null  int64
 23  txtPassageiro              37225 non-null   object
 24  txtTrecho                  37124 non-null   object
 25  numLote                    207575 non-null  int64
 26  numRessarcimento           44958 non-null   float64
 27  datPagamentoRestituicao    31 non-null      object
 28  vlrRestituicao             31 non-null      float64
 29  nuDeputadoId               207575 non-null  int64
 30  ideDocumento               207575 non-null  int64
 31  urlDocumento               157170 non-null  object
dtypes: float64(8), int64(11), object(13)
memory usage: 50.7+ MB

In [7]:
# Verificando os 3 últimos registros do dataframe
display(df.tail(3))

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
207572,Vanderlan Alves,2.964896e+09,234673.0,632.0,2023,CE,REPUBLICANOS,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,NaN,EM LOCACAO E COMERCIO DE VEICULOS LTDA,545.802.440/0020-9,18,4,2025-12-22T00:00:00,10400.0,0.0,10400.0,12,2025,0,NaN,NaN,2199423,NaN,NaN,NaN,3803,8033995,https://www.camara.leg.br/cota-parlamentar/not...
207573,Heloísa Helena,3.645032e+10,234788.0,633.0,2023,RJ,REDE,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,EDVALDO FRANCISCO DE OLIVEIRA 49191160120,323.738.120/0017-9,257,4,2025-12-19T00:00:00,194.4,0.0,194.4,12,2025,0,NaN,NaN,2206738,NaN,NaN,NaN,3804,8046527,https://www.camara.leg.br/cota-parlamentar/not...
207574,Heloísa Helena,3.645032e+10,234788.0,633.0,2023,RJ,REDE,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,MIL E UMA IDEIAS CONSULTORIA EM MARKETING E CO...,366.781.610/0018-6,188,0,2026-02-02T00:00:00,15000.0,0.0,15000.0,12,2025,0,NaN,NaN,2205674,NaN,NaN,NaN,3804,8044458,https://www.camara.leg.br/cota-parlamentar/doc...

In [8]:
# Verificando exemplos de registros na coluna 'numRessarcimento' que não sejam NaN
numRessarcimento_nao_nulos = df[df['numRessarcimento'].notna()]
numRessarcimento_nao_nulos

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
1194,Danilo Forte,1.213373e+10,62881.0,91.0,2023,CE,UNIÃO,57,10,TELEFONIA,0,NaN,CELULAR FUNCIONAL,000.000.000/0000-1,7894035,0,NaN,224.65,0.0,224.65,1,2025,0,NaN,NaN,0,0.0,NaN,NaN,2227,0,NaN
1195,Danilo Forte,1.213373e+10,62881.0,91.0,2023,CE,UNIÃO,57,10,TELEFONIA,0,NaN,CELULAR FUNCIONAL,000.000.000/0000-1,7894178,0,NaN,104.67,0.0,104.67,2,2025,0,NaN,NaN,0,0.0,NaN,NaN,2227,0,NaN
1196,Danilo Forte,1.213373e+10,62881.0,91.0,2023,CE,UNIÃO,57,10,TELEFONIA,0,NaN,CELULAR FUNCIONAL,000.000.000/0000-1,7947634,0,NaN,104.67,0.0,104.67,3,2025,0,NaN,NaN,0,0.0,NaN,NaN,2227,0,NaN
1197,Danilo Forte,1.213373e+10,62881.0,91.0,2023,CE,UNIÃO,57,10,TELEFONIA,0,NaN,CELULAR FUNCIONAL,000.000.000/0000-1,7958244,0,NaN,40.39,0.0,40.39,4,2025,0,NaN,NaN,0,0.0,NaN,NaN,2227,0,NaN
1198,Danilo Forte,1.213373e+10,62881.0,91.0,2023,CE,UNIÃO,57,10,TELEFONIA,0,NaN,CELULAR FUNCIONAL,000.000.000/0000-1,7959460,0,NaN,119.84,0.0,119.84,5,2025,0,NaN,NaN,0,0.0,NaN,NaN,2227,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207044,Nelinho Freitas,6.391578e+10,233218.0,616.0,2023,CE,MDB,57,998,PASSAGEM AÉREA - SIGEPA,0,NaN,GOL,NaN,1272139767353,0,2025-06-24T12:00:00,-37.00,0.0,-74.00,6,2025,0,RONDINELLE PEREIRA DE FREITAS,BSB/BSB,0,0.0,NaN,NaN,3793,342664,NaN
207045,Nelinho Freitas,6.391578e+10,233218.0,616.0,2023,CE,MDB,57,998,PASSAGEM AÉREA - SIGEPA,0,NaN,TAM,NaN,9572241410127,0,2025-07-15T12:00:00,1872.60,0.0,1872.60,7,2025,0,RONDINELLE PEREIRA DE FREITAS,JDO/FOR/BSB,0,0.0,NaN,NaN,3793,348822,NaN
207060,Paulo Lemos,4.018737e+10,233592.0,623.0,2023,AP,PSOL,57,10,TELEFONIA,0,NaN,RAMAL,000.000.000/0000-6,7985581,0,NaN,0.21,0.0,0.21,8,2025,0,NaN,NaN,0,0.0,NaN,NaN,3795,0,NaN
207272,Rafael Fera,9.966843e+10,233594.0,619.0,2023,RO,PODE,57,10,TELEFONIA,0,NaN,RAMAL,000.000.000/0000-6,7985581,0,NaN,1.20,0.0,1.20,8,2025,0,NaN,NaN,0,0.0,NaN,NaN,3794,0,NaN
207379,Samuel Santos,5.466624e+10,233598.0,625.0,2023,GO,PODE,57,10,TELEFONIA,0,NaN,RAMAL,000.000.000/0000-6,7985581,0,NaN,3.75,0.0,3.75,8,2025,0,NaN,NaN,0,0.0,NaN,NaN,3796,0,NaN

In [9]:
# Verificando exemplos de registros na coluna 'datPagamentoRestituicao' que não sejam NaN
datPagamentoRestituicao_nao_nulos = df[df['datPagamentoRestituicao'].notna()]
datPagamentoRestituicao_nao_nulos

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
2812,Arlindo Chinaglia,6.821146e+09,73433.0,336.0,2023,SP,PT,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO GRANDPRIX DE INTERLAGOS LTDA,169.299.630/0010-4,019314,1,2025-04-06T00:00:00,170.23,0.00,0.0,4,2025,0,NaN,NaN,2129268,NaN,2025-05-07T00:00:00,170.23,974,7901620,https://www.camara.leg.br/cota-parlamentar/doc...
3053,Arlindo Chinaglia,6.821146e+09,73433.0,336.0,2023,SP,PT,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,COOPERATIVA MISTA DE TRABALHO DOS MOTORISTAS A...,465.539.470/0012-0,849477774,1,2025-03-26T00:00:00,77.00,0.00,0.0,3,2025,0,NaN,NaN,2129272,NaN,2025-05-07T00:00:00,77.00,974,7903171,https://www.camara.leg.br/cota-parlamentar/doc...
7174,Luiz Carlos Hauly,8.682608e+09,73778.0,549.0,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,",auricio teixeira barbosa",269.698.068/39 -,sn,1,2025-06-27T00:00:00,36.60,0.00,0.0,6,2025,0,NaN,NaN,2148960,NaN,2025-07-09T00:00:00,36.60,824,7938485,https://www.camara.leg.br/cota-parlamentar/doc...
7176,Luiz Carlos Hauly,8.682608e+09,73778.0,549.0,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,ANDRE DOS SANTOS,298.603.538/83 -,sn,1,2025-06-19T00:00:00,70.00,0.00,0.0,6,2025,0,NaN,NaN,2148960,NaN,2025-07-09T00:00:00,70.00,824,7938471,https://www.camara.leg.br/cota-parlamentar/doc...
7187,Luiz Carlos Hauly,8.682608e+09,73778.0,549.0,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,MILOSO E MILOZO LTDA,107.701.940/0016-8,000000000620,1,2025-06-02T00:00:00,660.00,0.00,0.0,5,2025,0,NaN,NaN,2144384,NaN,2025-06-16T00:00:00,660.00,824,7929746,https://www.camara.leg.br/cota-parlamentar/doc...
23727,Laura Carneiro,7.940155e+10,74856.0,307.0,2023,RJ,PSD,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,NaN,SERV RIO TERCEIRIZAÇÃO E SERVIÇOS,104.798.610/0015-8,001829,1,2025-06-30T00:00:00,4200.00,0.00,0.0,6,2025,0,NaN,NaN,2150640,NaN,2025-07-08T00:00:00,4200.00,1118,7941710,https://www.camara.leg.br/cota-parlamentar/doc...
28695,Ana Paula Leão,5.203085e+10,107970.0,222.0,2023,MG,PP,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,Facebook Serviços Online do Brasil Ltda.,133.470.160/0011-7,125511406,0,2025-12-03T00:00:00,979.32,0.00,0.0,11,2025,0,NaN,NaN,2198113,NaN,2026-01-26T00:00:00,979.32,3664,8031374,https://www.camara.leg.br/cota-parlamentar/doc...
30579,Átila Lira,7.456870e+10,123086.0,109.0,2023,PI,PP,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,GOMO COMUNICAÇÂO LTDA,518.126.010/0013-0,119,0,2026-01-22T00:00:00,2000.00,0.00,0.0,12,2025,0,NaN,NaN,2204693,NaN,2026-02-26T00:00:00,214.42,3670,8043013,https://www.camara.leg.br/cota-parlamentar/doc...
69845,Afonso Motta,1.077730e+10,178835.0,490.0,2023,RS,PDT,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,NaN,ELF Locadora de Veículos Ltda,074.474.050/0011-1,25985,1,2025-09-02T00:00:00,4900.00,0.00,0.0,8,2025,0,NaN,NaN,2169554,NaN,2025-09-18T00:00:00,4900.00,2880,7976889,https://www.camara.leg.br/cota-parlamentar/doc...
72864,Evair Vieira de Melo,2.261266e+09,178871.0,274.0,2023,ES,PP,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,UBER DO BRASIL TECNOLOGIA LTDA.,178.956.460/0018-7,16.1,1,2025-10-16T00:00:00,40.86,0.00,0.0,10,2025,0,NaN,NaN,2183477,NaN,2025-12-12T00:00:00,40.86,2984,8003831,https://www.camara.leg.br/cota-parlamentar/doc...
72866,Evair Vieira de Melo,2.261266e+09,178871.0,274.0,2023,ES,PP,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,UBER DO BRASIL TECNOLOGIA LTDA.,178.956.460/0018-7,16.2,1,2025-10-16T00:00:00,51.82,0.00,0.0,10,2025,0,NaN,NaN,2183477,NaN,2025-12-12T00:00:00,51.82,2984,8003834,https://www.camara.leg.br/cota-parlamentar/doc...
84117,Miguel Lombardi,5.209980e+09,178985.0,378.0,2023,SP,PL,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,RODOPOSTO BANDEIRANTES NORTE LTDA,052.898.510/0011-0,307013,0,2025-06-29T00:00:00,161.12,0.00,0.0,6,2025,0,NaN,NaN,2149839,NaN,2025-07-24T00:00:00,161.12,2995,7939265,https://www.camara.leg.br/cota-parlamentar/doc...
108663,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,141992,0,2025-07-29T00:00:00,1625.40,0.00,0.0,7,2025,0,NaN,NaN,2165519,NaN,2025-10-21T00:00:00,1625.40,3344,7969334,https://www.camara.leg.br/cota-parlamentar/doc...
108665,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,142321,0,2025-08-06T00:00:00,15784.40,0.00,0.0,7,2025,0,NaN,NaN,2163132,NaN,2025-10-21T00:00:00,15784.41,3344,7965631,https://www.camara.leg.br/cota-parlamentar/doc...
108667,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,142322,0,2025-08-06T00:00:00,1344.33,0.00,0.0,7,2025,0,NaN,NaN,2164214,NaN,2025-10-21T00:00:00,1344.33,3344,7966850,https://www.camara.leg.br/cota-parlamentar/doc...
108669,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,142434,0,2025-08-08T00:00:00,3203.56,0.00,0.0,8,2025,0,NaN,NaN,2163141,NaN,2025-10-21T00:00:00,3203.56,3344,7965673,https://www.camara.leg.br/cota-parlamentar/doc...
108671,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,142614,0,2025-08-14T00:00:00,2055.42,0.00,0.0,8,2025,0,NaN,NaN,2164173,NaN,2025-10-21T00:00:00,2055.42,3344,7965679,https://www.camara.leg.br/cota-parlamentar/doc...
112498,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,1,4,2025-05-01T00:00:00,245.35,0.00,0.0,5,2025,0,NaN,NaN,2131548,NaN,2025-09-22T00:00:00,245.35,3391,7907582,https://www.camara.leg.br/cota-parlamentar/not...
112500,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,10147,4,2025-09-06T00:00:00,449.28,0.00,0.0,9,2025,0,NaN,NaN,2170221,NaN,2025-09-22T00:00:00,449.28,3391,7978270,https://www.camara.leg.br/cota-parlamentar/not...
112502,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,24,4,2025-05-03T00:00:00,224.68,0.00,0.0,5,2025,0,NaN,NaN,2131548,NaN,2025-09-22T00:00:00,224.68,3391,7907577,https://www.camara.leg.br/cota-parlamentar/not...
112504,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,270,4,2025-05-17T00:00:00,226.12,0.00,0.0,5,2025,0,NaN,NaN,2136590,NaN,2025-09-22T00:00:00,226.12,3391,7916735,https://www.camara.leg.br/cota-parlamentar/not...
112506,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,3724,4,2025-07-18T00:00:00,424.53,0.00,0.0,7,2025,0,NaN,NaN,2155369,NaN,2025-09-22T00:00:00,424.53,3391,7950646,https://www.camara.leg.br/cota-parlamentar/not...
112508,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,41,4,2025-05-05T10:26:02,299.98,0.00,0.0,5,2025,0,NaN,NaN,2131548,NaN,2025-09-22T00:00:00,299.98,3391,7907572,https://www.camara.leg.br/cota-parlamentar/not...
112510,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,559,4,2025-05-24T00:00:00,242.61,0.00,0.0,5,2025,0,NaN,NaN,2138363,NaN,2025-09-22T00:00:00,242.61,3391,7920174,https://www.camara.leg.br/cota-parlamentar/not...
112512,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,6062,4,2025-08-08T16:10:20,260.94,0.00,0.0,8,2025,0,NaN,NaN,2160985,NaN,2025-09-22T00:00:00,260.94,3391,7961248,https://www.camara.leg.br/cota-parlamentar/not...
112514,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,81,4,2025-05-08T15:48:58,350.00,0.00,0.0,5,2025,0,NaN,NaN,2134218,NaN,2025-09-22T00:00:00,350.00,3391,7912443,https://www.camara.leg.br/cota-parlamentar/not...
112516,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,8624,4,2025-08-31T00:00:00,388.17,0.00,0.0,8,2025,0,NaN,NaN,2167873,NaN,2025-09-22T00:00:00,388.17,3391,7973703,https://www.camara.leg.br/cota-parlamentar/not...
112518,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,895,4,2025-05-26T00:00:00,329.87,0.00,0.0,5,2025,0,NaN,NaN,2138363,NaN,2025-09-22T00:00:00,329.87,3391,7920177,https://www.camara.leg.br/cota-parlamentar/not...
136974,Gilvan da Federal,8.449012e+09,220526.0,281.0,2023,ES,PL,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,J WESLWY DE S PEREIRA,533.241.400/0018-1,00012,0,2025-05-02T00:00:00,7000.00,0.00,0.0,5,2025,0,NaN,NaN,2131904,NaN,2025-06-09T00:00:00,5870.97,3650,7908240,https://www.camara.leg.br/cota-parlamentar/doc...
196068,Carol Dartora,4.310203e+09,220704.0,444.0,2023,PR,PT,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,SANEPAR,764.840.130/0014-5,270,1,2025-05-27T00:00:00,176.34,6.08,0.0,5,2025,0,NaN,NaN,2145810,NaN,2025-07-09T00:00:00,170.26,3632,7932439,https://www.camara.leg.br/cota-parlamentar/doc...
203055,Saulo Pedroso,3.042023e+10,226837.0,559.0,2023,SP,PSD,57,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,0,NaN,VA DOS SANTOS RESTAURANTE E LACHONETE,349.788.620/0010-5,000477,0,2025-05-05T00:00:00,200.00,0.00,0.0,5,2025,0,NaN,NaN,2132641,NaN,2025-05-21T00:00:00,200.00,3748,7909605,https://www.camara.leg.br/cota-parlamentar/doc...

In [10]:
# Verificando exemplos de registros na coluna 'datPagamentoRestituicao' que não sejam NaN
vlrRestituicao_nao_nulos = df[df['vlrRestituicao'].notna()]
vlrRestituicao_nao_nulos

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
2812,Arlindo Chinaglia,6.821146e+09,73433.0,336.0,2023,SP,PT,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO GRANDPRIX DE INTERLAGOS LTDA,169.299.630/0010-4,019314,1,2025-04-06T00:00:00,170.23,0.00,0.0,4,2025,0,NaN,NaN,2129268,NaN,2025-05-07T00:00:00,170.23,974,7901620,https://www.camara.leg.br/cota-parlamentar/doc...
3053,Arlindo Chinaglia,6.821146e+09,73433.0,336.0,2023,SP,PT,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,COOPERATIVA MISTA DE TRABALHO DOS MOTORISTAS A...,465.539.470/0012-0,849477774,1,2025-03-26T00:00:00,77.00,0.00,0.0,3,2025,0,NaN,NaN,2129272,NaN,2025-05-07T00:00:00,77.00,974,7903171,https://www.camara.leg.br/cota-parlamentar/doc...
7174,Luiz Carlos Hauly,8.682608e+09,73778.0,549.0,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,",auricio teixeira barbosa",269.698.068/39 -,sn,1,2025-06-27T00:00:00,36.60,0.00,0.0,6,2025,0,NaN,NaN,2148960,NaN,2025-07-09T00:00:00,36.60,824,7938485,https://www.camara.leg.br/cota-parlamentar/doc...
7176,Luiz Carlos Hauly,8.682608e+09,73778.0,549.0,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,ANDRE DOS SANTOS,298.603.538/83 -,sn,1,2025-06-19T00:00:00,70.00,0.00,0.0,6,2025,0,NaN,NaN,2148960,NaN,2025-07-09T00:00:00,70.00,824,7938471,https://www.camara.leg.br/cota-parlamentar/doc...
7187,Luiz Carlos Hauly,8.682608e+09,73778.0,549.0,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,MILOSO E MILOZO LTDA,107.701.940/0016-8,000000000620,1,2025-06-02T00:00:00,660.00,0.00,0.0,5,2025,0,NaN,NaN,2144384,NaN,2025-06-16T00:00:00,660.00,824,7929746,https://www.camara.leg.br/cota-parlamentar/doc...
23727,Laura Carneiro,7.940155e+10,74856.0,307.0,2023,RJ,PSD,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,NaN,SERV RIO TERCEIRIZAÇÃO E SERVIÇOS,104.798.610/0015-8,001829,1,2025-06-30T00:00:00,4200.00,0.00,0.0,6,2025,0,NaN,NaN,2150640,NaN,2025-07-08T00:00:00,4200.00,1118,7941710,https://www.camara.leg.br/cota-parlamentar/doc...
28695,Ana Paula Leão,5.203085e+10,107970.0,222.0,2023,MG,PP,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,Facebook Serviços Online do Brasil Ltda.,133.470.160/0011-7,125511406,0,2025-12-03T00:00:00,979.32,0.00,0.0,11,2025,0,NaN,NaN,2198113,NaN,2026-01-26T00:00:00,979.32,3664,8031374,https://www.camara.leg.br/cota-parlamentar/doc...
30579,Átila Lira,7.456870e+10,123086.0,109.0,2023,PI,PP,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,GOMO COMUNICAÇÂO LTDA,518.126.010/0013-0,119,0,2026-01-22T00:00:00,2000.00,0.00,0.0,12,2025,0,NaN,NaN,2204693,NaN,2026-02-26T00:00:00,214.42,3670,8043013,https://www.camara.leg.br/cota-parlamentar/doc...
69845,Afonso Motta,1.077730e+10,178835.0,490.0,2023,RS,PDT,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,NaN,ELF Locadora de Veículos Ltda,074.474.050/0011-1,25985,1,2025-09-02T00:00:00,4900.00,0.00,0.0,8,2025,0,NaN,NaN,2169554,NaN,2025-09-18T00:00:00,4900.00,2880,7976889,https://www.camara.leg.br/cota-parlamentar/doc...
72864,Evair Vieira de Melo,2.261266e+09,178871.0,274.0,2023,ES,PP,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,UBER DO BRASIL TECNOLOGIA LTDA.,178.956.460/0018-7,16.1,1,2025-10-16T00:00:00,40.86,0.00,0.0,10,2025,0,NaN,NaN,2183477,NaN,2025-12-12T00:00:00,40.86,2984,8003831,https://www.camara.leg.br/cota-parlamentar/doc...
72866,Evair Vieira de Melo,2.261266e+09,178871.0,274.0,2023,ES,PP,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,NaN,UBER DO BRASIL TECNOLOGIA LTDA.,178.956.460/0018-7,16.2,1,2025-10-16T00:00:00,51.82,0.00,0.0,10,2025,0,NaN,NaN,2183477,NaN,2025-12-12T00:00:00,51.82,2984,8003834,https://www.camara.leg.br/cota-parlamentar/doc...
84117,Miguel Lombardi,5.209980e+09,178985.0,378.0,2023,SP,PL,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,RODOPOSTO BANDEIRANTES NORTE LTDA,052.898.510/0011-0,307013,0,2025-06-29T00:00:00,161.12,0.00,0.0,6,2025,0,NaN,NaN,2149839,NaN,2025-07-24T00:00:00,161.12,2995,7939265,https://www.camara.leg.br/cota-parlamentar/doc...
108663,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,141992,0,2025-07-29T00:00:00,1625.40,0.00,0.0,7,2025,0,NaN,NaN,2165519,NaN,2025-10-21T00:00:00,1625.40,3344,7969334,https://www.camara.leg.br/cota-parlamentar/doc...
108665,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,142321,0,2025-08-06T00:00:00,15784.40,0.00,0.0,7,2025,0,NaN,NaN,2163132,NaN,2025-10-21T00:00:00,15784.41,3344,7965631,https://www.camara.leg.br/cota-parlamentar/doc...
108667,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,142322,0,2025-08-06T00:00:00,1344.33,0.00,0.0,7,2025,0,NaN,NaN,2164214,NaN,2025-10-21T00:00:00,1344.33,3344,7966850,https://www.camara.leg.br/cota-parlamentar/doc...
108669,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,142434,0,2025-08-08T00:00:00,3203.56,0.00,0.0,8,2025,0,NaN,NaN,2163141,NaN,2025-10-21T00:00:00,3203.56,3344,7965673,https://www.camara.leg.br/cota-parlamentar/doc...
108671,Helio Lopes,8.917437e+08,204444.0,303.0,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,NaN,IBIS SOROCABA,024.197.650/0205-9,142614,0,2025-08-14T00:00:00,2055.42,0.00,0.0,8,2025,0,NaN,NaN,2164173,NaN,2025-10-21T00:00:00,2055.42,3344,7965679,https://www.camara.leg.br/cota-parlamentar/doc...
112498,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,1,4,2025-05-01T00:00:00,245.35,0.00,0.0,5,2025,0,NaN,NaN,2131548,NaN,2025-09-22T00:00:00,245.35,3391,7907582,https://www.camara.leg.br/cota-parlamentar/not...
112500,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,10147,4,2025-09-06T00:00:00,449.28,0.00,0.0,9,2025,0,NaN,NaN,2170221,NaN,2025-09-22T00:00:00,449.28,3391,7978270,https://www.camara.leg.br/cota-parlamentar/not...
112502,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,24,4,2025-05-03T00:00:00,224.68,0.00,0.0,5,2025,0,NaN,NaN,2131548,NaN,2025-09-22T00:00:00,224.68,3391,7907577,https://www.camara.leg.br/cota-parlamentar/not...
112504,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,270,4,2025-05-17T00:00:00,226.12,0.00,0.0,5,2025,0,NaN,NaN,2136590,NaN,2025-09-22T00:00:00,226.12,3391,7916735,https://www.camara.leg.br/cota-parlamentar/not...
112506,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,3724,4,2025-07-18T00:00:00,424.53,0.00,0.0,7,2025,0,NaN,NaN,2155369,NaN,2025-09-22T00:00:00,424.53,3391,7950646,https://www.camara.leg.br/cota-parlamentar/not...
112508,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,41,4,2025-05-05T10:26:02,299.98,0.00,0.0,5,2025,0,NaN,NaN,2131548,NaN,2025-09-22T00:00:00,299.98,3391,7907572,https://www.camara.leg.br/cota-parlamentar/not...
112510,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,559,4,2025-05-24T00:00:00,242.61,0.00,0.0,5,2025,0,NaN,NaN,2138363,NaN,2025-09-22T00:00:00,242.61,3391,7920174,https://www.camara.leg.br/cota-parlamentar/not...
112512,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,6062,4,2025-08-08T16:10:20,260.94,0.00,0.0,8,2025,0,NaN,NaN,2160985,NaN,2025-09-22T00:00:00,260.94,3391,7961248,https://www.camara.leg.br/cota-parlamentar/not...
112514,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,81,4,2025-05-08T15:48:58,350.00,0.00,0.0,5,2025,0,NaN,NaN,2134218,NaN,2025-09-22T00:00:00,350.00,3391,7912443,https://www.camara.leg.br/cota-parlamentar/not...
112516,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,8624,4,2025-08-31T00:00:00,388.17,0.00,0.0,8,2025,0,NaN,NaN,2167873,NaN,2025-09-22T00:00:00,388.17,3391,7973703,https://www.camara.leg.br/cota-parlamentar/not...
112518,Juninho do Pneu,7.845800e+09,204457.0,308.0,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,895,4,2025-05-26T00:00:00,329.87,0.00,0.0,5,2025,0,NaN,NaN,2138363,NaN,2025-09-22T00:00:00,329.87,3391,7920177,https://www.camara.leg.br/cota-parlamentar/not...
136974,Gilvan da Federal,8.449012e+09,220526.0,281.0,2023,ES,PL,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,NaN,J WESLWY DE S PEREIRA,533.241.400/0018-1,00012,0,2025-05-02T00:00:00,7000.00,0.00,0.0,5,2025,0,NaN,NaN,2131904,NaN,2025-06-09T00:00:00,5870.97,3650,7908240,https://www.camara.leg.br/cota-parlamentar/doc...
196068,Carol Dartora,4.310203e+09,220704.0,444.0,2023,PR,PT,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,NaN,SANEPAR,764.840.130/0014-5,270,1,2025-05-27T00:00:00,176.34,6.08,0.0,5,2025,0,NaN,NaN,2145810,NaN,2025-07-09T00:00:00,170.26,3632,7932439,https://www.camara.leg.br/cota-parlamentar/doc...
203055,Saulo Pedroso,3.042023e+10,226837.0,559.0,2023,SP,PSD,57,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,0,NaN,VA DOS SANTOS RESTAURANTE E LACHONETE,349.788.620/0010-5,000477,0,2025-05-05T00:00:00,200.00,0.00,0.0,5,2025,0,NaN,NaN,2132641,NaN,2025-05-21T00:00:00,200.00,3748,7909605,https://www.camara.leg.br/cota-parlamentar/doc...

### 2. Modificando os tipos de dados das colunas do dataframe

In [11]:
# Modificando os tipos das colunas de float64 para int64 e, depois, para string
df['cpf'] = df['cpf'].fillna(0).astype('int64').astype('string')
df['ideCadastro'] = df['ideCadastro'].fillna(0).astype('int64').astype('string')
df['nuCarteiraParlamentar'] = df['nuCarteiraParlamentar'].fillna(0).astype('int64').astype('string')
df['numRessarcimento'] = df['numRessarcimento'].fillna(0).astype('int64').astype('string')

# Modificando os tipos das colunas de object para string
df['txNomeParlamentar'] = df['txNomeParlamentar'].astype('string')
df['sgUF'] = df['sgUF'].astype('string')
df['sgPartido'] = df['sgPartido'].astype('string')
df['txtDescricao'] = df['txtDescricao'].astype('string')
df['txtDescricaoEspecificacao'] = df['txtDescricaoEspecificacao'].astype('string')
df['txtFornecedor'] = df['txtFornecedor'].astype('string')
df['txtCNPJCPF'] = df['txtCNPJCPF'].astype('string')
df['txtNumero'] = df['txtNumero'].astype('string')
df['txtPassageiro'] = df['txtPassageiro'].astype('string')
df['txtTrecho'] = df['txtTrecho'].astype('string')
df['urlDocumento'] = df['urlDocumento'].astype('string')

# Modificando os tipos das colunas de int64 para string
df['codLegislatura'] = df['codLegislatura'].astype('string')
df['numSubCota'] = df['numSubCota'].astype('string')
df['numEspecificacaoSubCota'] = df['numEspecificacaoSubCota'].astype('string')
df['indTipoDocumento'] = df['indTipoDocumento'].astype('string')
df['numLote'] = df['numLote'].astype('string')
df['nuDeputadoId'] = df['nuDeputadoId'].astype('string')
df['ideDocumento'] = df['ideDocumento'].astype('string')

# Modificando os tipos das colunas de object para datetime
df['datEmissao'] = pd.to_datetime(df['datEmissao'])
df['datPagamentoRestituicao'] = pd.to_datetime(df['datPagamentoRestituicao'])

In [12]:
# Exibindo informações resumidas do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207575 entries, 0 to 207574
Data columns (total 32 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   txNomeParlamentar          207575 non-null  string
 1   cpf                        207575 non-null  string
 2   ideCadastro                207575 non-null  string
 3   nuCarteiraParlamentar      207575 non-null  string
 4   nuLegislatura              207575 non-null  int64
 5   sgUF                       206639 non-null  string
 6   sgPartido                  206639 non-null  string
 7   codLegislatura             207575 non-null  string
 8   numSubCota                 207575 non-null  string
 9   txtDescricao               207575 non-null  string
 10  numEspecificacaoSubCota    207575 non-null  string
 11  txtDescricaoEspecificacao  71467 non-null   string
 12  txtFornecedor              207575 non-null  string
 13  txtCNPJCPF                 170996 non-null  string
 14  txtNumero                  207575 non-null  string
 15  indTipoDocumento           207575 non-null  string
 16  datEmissao                 199741 non-null  datetime64[ns]
 17  vlrDocumento               207575 non-null  float64
 18  vlrGlosa                   207575 non-null  float64
 19  vlrLiquido                 207575 non-null  float64
 20  numMes                     207575 non-null  int64
 21  numAno                     207575 non-null  int64
 22  numParcela                 207575 non-null  int64
 23  txtPassageiro              37225 non-null   string
 24  txtTrecho                  37124 non-null   string
 25  numLote                    207575 non-null  string
 26  numRessarcimento           207575 non-null  string
 27  datPagamentoRestituicao    31 non-null      datetime64[ns]
 28  vlrRestituicao             31 non-null      float64
 29  nuDeputadoId               207575 non-null  string
 30  ideDocumento               207575 non-null  string
 31  urlDocumento               157170 non-null  string
dtypes: datetime64[ns](2), float64(4), int64(4), string(22)
memory usage: 50.7 MB

In [13]:
# Verificando exemplos de registros na coluna 'numRessarcimento' que não sejam NaN
numRessarcimento_nao_nulos = df[df['numRessarcimento'].notna()]
numRessarcimento_nao_nulos

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
0,LID.GOV-CD,0,0,0,2023,<NA>,<NA>,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,1984,0,2025-02-07,1467.0,0.0,1467.0,2,2025,0,<NA>,<NA>,2115566,0,NaT,NaN,2812,7877589,https://www.camara.leg.br/cota-parlamentar/doc...
1,LID.GOV-CD,0,0,0,2023,<NA>,<NA>,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,2060,0,2025-03-11,1467.0,0.0,1467.0,3,2025,0,<NA>,<NA>,2123760,0,NaT,NaN,2812,7892756,https://www.camara.leg.br/cota-parlamentar/doc...
2,LID.GOV-CD,0,0,0,2023,<NA>,<NA>,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,2143,0,2025-04-11,1467.0,0.0,1467.0,4,2025,0,<NA>,<NA>,2131750,0,NaT,NaN,2812,7907982,https://www.camara.leg.br/cota-parlamentar/doc...
3,LID.GOV-CD,0,0,0,2023,<NA>,<NA>,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,2219,0,2025-05-12,1467.0,0.0,1467.0,5,2025,0,<NA>,<NA>,2139804,0,NaT,NaN,2812,7923034,https://www.camara.leg.br/cota-parlamentar/doc...
4,LID.GOV-CD,0,0,0,2023,<NA>,<NA>,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,AMORETTO CAFES EXPRESSO LTDA,085.324.290/0013-1,2298,0,2025-06-03,1467.0,0.0,1467.0,6,2025,0,<NA>,<NA>,2150181,0,NaT,NaN,2812,7940865,https://www.camara.leg.br/cota-parlamentar/doc...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207570,Vanderlan Alves,2964896380,234673,632,2023,CE,REPUBLICANOS,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,TAMIRES MEDEIROS SALES,519.967.580/0016-2,30,0,2025-12-26,4150.0,0.0,4150.0,12,2025,0,<NA>,<NA>,2199991,0,NaT,NaN,3803,8034979,https://www.camara.leg.br/cota-parlamentar/doc...
207571,Vanderlan Alves,2964896380,234673,632,2023,CE,REPUBLICANOS,57,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,0,<NA>,50.340.443 LAISY OLIVEIRA COSTA DE LIMA,503.404.430/0010-8,13421,4,2025-12-18,80.0,0.0,80.0,12,2025,0,<NA>,<NA>,2198808,0,NaT,NaN,3803,8032796,https://www.camara.leg.br/cota-parlamentar/not...
207572,Vanderlan Alves,2964896380,234673,632,2023,CE,REPUBLICANOS,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,<NA>,EM LOCACAO E COMERCIO DE VEICULOS LTDA,545.802.440/0020-9,18,4,2025-12-22,10400.0,0.0,10400.0,12,2025,0,<NA>,<NA>,2199423,0,NaT,NaN,3803,8033995,https://www.camara.leg.br/cota-parlamentar/not...
207573,Heloísa Helena,36450316420,234788,633,2023,RJ,REDE,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,EDVALDO FRANCISCO DE OLIVEIRA 49191160120,323.738.120/0017-9,257,4,2025-12-19,194.4,0.0,194.4,12,2025,0,<NA>,<NA>,2206738,0,NaT,NaN,3804,8046527,https://www.camara.leg.br/cota-parlamentar/not...
207574,Heloísa Helena,36450316420,234788,633,2023,RJ,REDE,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,MIL E UMA IDEIAS CONSULTORIA EM MARKETING E CO...,366.781.610/0018-6,188,0,2026-02-02,15000.0,0.0,15000.0,12,2025,0,<NA>,<NA>,2205674,0,NaT,NaN,3804,8044458,https://www.camara.leg.br/cota-parlamentar/doc...

In [14]:
# Verificando exemplos de registros na coluna 'datPagamentoRestituicao' que não sejam NaN
datPagamentoRestituicao_nao_nulos = df[df['datPagamentoRestituicao'].notna()]
datPagamentoRestituicao_nao_nulos

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
2812,Arlindo Chinaglia,6821146187,73433,336,2023,SP,PT,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO GRANDPRIX DE INTERLAGOS LTDA,169.299.630/0010-4,019314,1,2025-04-06 00:00:00,170.23,0.00,0.0,4,2025,0,<NA>,<NA>,2129268,0,2025-05-07,170.23,974,7901620,https://www.camara.leg.br/cota-parlamentar/doc...
3053,Arlindo Chinaglia,6821146187,73433,336,2023,SP,PT,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,COOPERATIVA MISTA DE TRABALHO DOS MOTORISTAS A...,465.539.470/0012-0,849477774,1,2025-03-26 00:00:00,77.00,0.00,0.0,3,2025,0,<NA>,<NA>,2129272,0,2025-05-07,77.00,974,7903171,https://www.camara.leg.br/cota-parlamentar/doc...
7174,Luiz Carlos Hauly,8682607972,73778,549,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,",auricio teixeira barbosa",269.698.068/39 -,sn,1,2025-06-27 00:00:00,36.60,0.00,0.0,6,2025,0,<NA>,<NA>,2148960,0,2025-07-09,36.60,824,7938485,https://www.camara.leg.br/cota-parlamentar/doc...
7176,Luiz Carlos Hauly,8682607972,73778,549,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,ANDRE DOS SANTOS,298.603.538/83 -,sn,1,2025-06-19 00:00:00,70.00,0.00,0.0,6,2025,0,<NA>,<NA>,2148960,0,2025-07-09,70.00,824,7938471,https://www.camara.leg.br/cota-parlamentar/doc...
7187,Luiz Carlos Hauly,8682607972,73778,549,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,MILOSO E MILOZO LTDA,107.701.940/0016-8,000000000620,1,2025-06-02 00:00:00,660.00,0.00,0.0,5,2025,0,<NA>,<NA>,2144384,0,2025-06-16,660.00,824,7929746,https://www.camara.leg.br/cota-parlamentar/doc...
23727,Laura Carneiro,79401546720,74856,307,2023,RJ,PSD,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,<NA>,SERV RIO TERCEIRIZAÇÃO E SERVIÇOS,104.798.610/0015-8,001829,1,2025-06-30 00:00:00,4200.00,0.00,0.0,6,2025,0,<NA>,<NA>,2150640,0,2025-07-08,4200.00,1118,7941710,https://www.camara.leg.br/cota-parlamentar/doc...
28695,Ana Paula Leão,52030849634,107970,222,2023,MG,PP,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,Facebook Serviços Online do Brasil Ltda.,133.470.160/0011-7,125511406,0,2025-12-03 00:00:00,979.32,0.00,0.0,11,2025,0,<NA>,<NA>,2198113,0,2026-01-26,979.32,3664,8031374,https://www.camara.leg.br/cota-parlamentar/doc...
30579,Átila Lira,74568701368,123086,109,2023,PI,PP,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,GOMO COMUNICAÇÂO LTDA,518.126.010/0013-0,119,0,2026-01-22 00:00:00,2000.00,0.00,0.0,12,2025,0,<NA>,<NA>,2204693,0,2026-02-26,214.42,3670,8043013,https://www.camara.leg.br/cota-parlamentar/doc...
69845,Afonso Motta,10777296004,178835,490,2023,RS,PDT,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,<NA>,ELF Locadora de Veículos Ltda,074.474.050/0011-1,25985,1,2025-09-02 00:00:00,4900.00,0.00,0.0,8,2025,0,<NA>,<NA>,2169554,0,2025-09-18,4900.00,2880,7976889,https://www.camara.leg.br/cota-parlamentar/doc...
72864,Evair Vieira de Melo,2261265794,178871,274,2023,ES,PP,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,UBER DO BRASIL TECNOLOGIA LTDA.,178.956.460/0018-7,16.1,1,2025-10-16 00:00:00,40.86,0.00,0.0,10,2025,0,<NA>,<NA>,2183477,0,2025-12-12,40.86,2984,8003831,https://www.camara.leg.br/cota-parlamentar/doc...
72866,Evair Vieira de Melo,2261265794,178871,274,2023,ES,PP,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,UBER DO BRASIL TECNOLOGIA LTDA.,178.956.460/0018-7,16.2,1,2025-10-16 00:00:00,51.82,0.00,0.0,10,2025,0,<NA>,<NA>,2183477,0,2025-12-12,51.82,2984,8003834,https://www.camara.leg.br/cota-parlamentar/doc...
84117,Miguel Lombardi,5209979806,178985,378,2023,SP,PL,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,RODOPOSTO BANDEIRANTES NORTE LTDA,052.898.510/0011-0,307013,0,2025-06-29 00:00:00,161.12,0.00,0.0,6,2025,0,<NA>,<NA>,2149839,0,2025-07-24,161.12,2995,7939265,https://www.camara.leg.br/cota-parlamentar/doc...
108663,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,141992,0,2025-07-29 00:00:00,1625.40,0.00,0.0,7,2025,0,<NA>,<NA>,2165519,0,2025-10-21,1625.40,3344,7969334,https://www.camara.leg.br/cota-parlamentar/doc...
108665,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,142321,0,2025-08-06 00:00:00,15784.40,0.00,0.0,7,2025,0,<NA>,<NA>,2163132,0,2025-10-21,15784.41,3344,7965631,https://www.camara.leg.br/cota-parlamentar/doc...
108667,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,142322,0,2025-08-06 00:00:00,1344.33,0.00,0.0,7,2025,0,<NA>,<NA>,2164214,0,2025-10-21,1344.33,3344,7966850,https://www.camara.leg.br/cota-parlamentar/doc...
108669,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,142434,0,2025-08-08 00:00:00,3203.56,0.00,0.0,8,2025,0,<NA>,<NA>,2163141,0,2025-10-21,3203.56,3344,7965673,https://www.camara.leg.br/cota-parlamentar/doc...
108671,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,142614,0,2025-08-14 00:00:00,2055.42,0.00,0.0,8,2025,0,<NA>,<NA>,2164173,0,2025-10-21,2055.42,3344,7965679,https://www.camara.leg.br/cota-parlamentar/doc...
112498,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,1,4,2025-05-01 00:00:00,245.35,0.00,0.0,5,2025,0,<NA>,<NA>,2131548,0,2025-09-22,245.35,3391,7907582,https://www.camara.leg.br/cota-parlamentar/not...
112500,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,10147,4,2025-09-06 00:00:00,449.28,0.00,0.0,9,2025,0,<NA>,<NA>,2170221,0,2025-09-22,449.28,3391,7978270,https://www.camara.leg.br/cota-parlamentar/not...
112502,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,24,4,2025-05-03 00:00:00,224.68,0.00,0.0,5,2025,0,<NA>,<NA>,2131548,0,2025-09-22,224.68,3391,7907577,https://www.camara.leg.br/cota-parlamentar/not...
112504,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,270,4,2025-05-17 00:00:00,226.12,0.00,0.0,5,2025,0,<NA>,<NA>,2136590,0,2025-09-22,226.12,3391,7916735,https://www.camara.leg.br/cota-parlamentar/not...
112506,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,3724,4,2025-07-18 00:00:00,424.53,0.00,0.0,7,2025,0,<NA>,<NA>,2155369,0,2025-09-22,424.53,3391,7950646,https://www.camara.leg.br/cota-parlamentar/not...
112508,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,41,4,2025-05-05 10:26:02,299.98,0.00,0.0,5,2025,0,<NA>,<NA>,2131548,0,2025-09-22,299.98,3391,7907572,https://www.camara.leg.br/cota-parlamentar/not...
112510,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,559,4,2025-05-24 00:00:00,242.61,0.00,0.0,5,2025,0,<NA>,<NA>,2138363,0,2025-09-22,242.61,3391,7920174,https://www.camara.leg.br/cota-parlamentar/not...
112512,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,6062,4,2025-08-08 16:10:20,260.94,0.00,0.0,8,2025,0,<NA>,<NA>,2160985,0,2025-09-22,260.94,3391,7961248,https://www.camara.leg.br/cota-parlamentar/not...
112514,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,81,4,2025-05-08 15:48:58,350.00,0.00,0.0,5,2025,0,<NA>,<NA>,2134218,0,2025-09-22,350.00,3391,7912443,https://www.camara.leg.br/cota-parlamentar/not...
112516,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,8624,4,2025-08-31 00:00:00,388.17,0.00,0.0,8,2025,0,<NA>,<NA>,2167873,0,2025-09-22,388.17,3391,7973703,https://www.camara.leg.br/cota-parlamentar/not...
112518,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,895,4,2025-05-26 00:00:00,329.87,0.00,0.0,5,2025,0,<NA>,<NA>,2138363,0,2025-09-22,329.87,3391,7920177,https://www.camara.leg.br/cota-parlamentar/not...
136974,Gilvan da Federal,8449011728,220526,281,2023,ES,PL,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,J WESLWY DE S PEREIRA,533.241.400/0018-1,00012,0,2025-05-02 00:00:00,7000.00,0.00,0.0,5,2025,0,<NA>,<NA>,2131904,0,2025-06-09,5870.97,3650,7908240,https://www.camara.leg.br/cota-parlamentar/doc...
196068,Carol Dartora,4310202993,220704,444,2023,PR,PT,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,SANEPAR,764.840.130/0014-5,270,1,2025-05-27 00:00:00,176.34,6.08,0.0,5,2025,0,<NA>,<NA>,2145810,0,2025-07-09,170.26,3632,7932439,https://www.camara.leg.br/cota-parlamentar/doc...
203055,Saulo Pedroso,30420230874,226837,559,2023,SP,PSD,57,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,0,<NA>,VA DOS SANTOS RESTAURANTE E LACHONETE,349.788.620/0010-5,000477,0,2025-05-05 00:00:00,200.00,0.00,0.0,5,2025,0,<NA>,<NA>,2132641,0,2025-05-21,200.00,3748,7909605,https://www.camara.leg.br/cota-parlamentar/doc...

In [15]:
# Verificando quantidade de valores nulos em cada coluna
df.isna().sum()

txNomeParlamentar                 0
cpf                               0
ideCadastro                       0
nuCarteiraParlamentar             0
nuLegislatura                     0
sgUF                            936
sgPartido                       936
codLegislatura                    0
numSubCota                        0
txtDescricao                      0
numEspecificacaoSubCota           0
txtDescricaoEspecificacao    136108
txtFornecedor                     0
txtCNPJCPF                    36579
txtNumero                         0
indTipoDocumento                  0
datEmissao                     7834
vlrDocumento                      0
vlrGlosa                          0
vlrLiquido                        0
numMes                            0
numAno                            0
numParcela                        0
txtPassageiro                170350
txtTrecho                    170451
numLote                           0
numRessarcimento                  0
datPagamentoRestituicao      207544
vlrRestituicao               207544
nuDeputadoId                      0
ideDocumento                      0
urlDocumento                  50405
dtype: int64

In [16]:
# Verificando os 3 últimos registros do dataframe
display(df.tail(3))

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento
207572,Vanderlan Alves,2964896380,234673,632,2023,CE,REPUBLICANOS,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,<NA>,EM LOCACAO E COMERCIO DE VEICULOS LTDA,545.802.440/0020-9,18,4,2025-12-22,10400.0,0.0,10400.0,12,2025,0,<NA>,<NA>,2199423,0,NaT,NaN,3803,8033995,https://www.camara.leg.br/cota-parlamentar/not...
207573,Heloísa Helena,36450316420,234788,633,2023,RJ,REDE,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,EDVALDO FRANCISCO DE OLIVEIRA 49191160120,323.738.120/0017-9,257,4,2025-12-19,194.4,0.0,194.4,12,2025,0,<NA>,<NA>,2206738,0,NaT,NaN,3804,8046527,https://www.camara.leg.br/cota-parlamentar/not...
207574,Heloísa Helena,36450316420,234788,633,2023,RJ,REDE,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,MIL E UMA IDEIAS CONSULTORIA EM MARKETING E CO...,366.781.610/0018-6,188,0,2026-02-02,15000.0,0.0,15000.0,12,2025,0,<NA>,<NA>,2205674,0,NaT,NaN,3804,8044458,https://www.camara.leg.br/cota-parlamentar/doc...

### 3. Criando novas colunas a partir da 'datEmissao' já existente

In [17]:
df['dia_datEmissao'] = df['datEmissao'].dt.day
df['mes_datEmissao'] = df['datEmissao'].dt.month
df['ano_datEmissao'] = df['datEmissao'].dt.year

In [18]:
# Verificando os 3 últimos registros do dataframe
display(df.tail(3))

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento,dia_datEmissao,mes_datEmissao,ano_datEmissao
207572,Vanderlan Alves,2964896380,234673,632,2023,CE,REPUBLICANOS,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,<NA>,EM LOCACAO E COMERCIO DE VEICULOS LTDA,545.802.440/0020-9,18,4,2025-12-22,10400.0,0.0,10400.0,12,2025,0,<NA>,<NA>,2199423,0,NaT,NaN,3803,8033995,https://www.camara.leg.br/cota-parlamentar/not...,22.0,12.0,2025.0
207573,Heloísa Helena,36450316420,234788,633,2023,RJ,REDE,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,EDVALDO FRANCISCO DE OLIVEIRA 49191160120,323.738.120/0017-9,257,4,2025-12-19,194.4,0.0,194.4,12,2025,0,<NA>,<NA>,2206738,0,NaT,NaN,3804,8046527,https://www.camara.leg.br/cota-parlamentar/not...,19.0,12.0,2025.0
207574,Heloísa Helena,36450316420,234788,633,2023,RJ,REDE,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,MIL E UMA IDEIAS CONSULTORIA EM MARKETING E CO...,366.781.610/0018-6,188,0,2026-02-02,15000.0,0.0,15000.0,12,2025,0,<NA>,<NA>,2205674,0,NaT,NaN,3804,8044458,https://www.camara.leg.br/cota-parlamentar/doc...,2.0,2.0,2026.0

#### 3.1 Alterando tipo de dados das colunas criadas

In [19]:
# Verificando os tipos de dados das colunas criadas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207575 entries, 0 to 207574
Data columns (total 35 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   txNomeParlamentar          207575 non-null  string
 1   cpf                        207575 non-null  string
 2   ideCadastro                207575 non-null  string
 3   nuCarteiraParlamentar      207575 non-null  string
 4   nuLegislatura              207575 non-null  int64
 5   sgUF                       206639 non-null  string
 6   sgPartido                  206639 non-null  string
 7   codLegislatura             207575 non-null  string
 8   numSubCota                 207575 non-null  string
 9   txtDescricao               207575 non-null  string
 10  numEspecificacaoSubCota    207575 non-null  string
 11  txtDescricaoEspecificacao  71467 non-null   string
 12  txtFornecedor              207575 non-null  string
 13  txtCNPJCPF                 170996 non-null  string
 14  txtNumero                  207575 non-null  string
 15  indTipoDocumento           207575 non-null  string
 16  datEmissao                 199741 non-null  datetime64[ns]
 17  vlrDocumento               207575 non-null  float64
 18  vlrGlosa                   207575 non-null  float64
 19  vlrLiquido                 207575 non-null  float64
 20  numMes                     207575 non-null  int64
 21  numAno                     207575 non-null  int64
 22  numParcela                 207575 non-null  int64
 23  txtPassageiro              37225 non-null   string
 24  txtTrecho                  37124 non-null   string
 25  numLote                    207575 non-null  string
 26  numRessarcimento           207575 non-null  string
 27  datPagamentoRestituicao    31 non-null      datetime64[ns]
 28  vlrRestituicao             31 non-null      float64
 29  nuDeputadoId               207575 non-null  string
 30  ideDocumento               207575 non-null  string
 31  urlDocumento               157170 non-null  string
 32  dia_datEmissao             199741 non-null  float64
 33  mes_datEmissao             199741 non-null  float64
 34  ano_datEmissao             199741 non-null  float64
dtypes: datetime64[ns](2), float64(7), int64(4), string(22)
memory usage: 55.4 MB

In [20]:
# Modificando o tipo de dados das colunas criadas de float64 para int64
df['dia_datEmissao'] = df['dia_datEmissao'].fillna(0).astype('int64')
df['mes_datEmissao'] = df['mes_datEmissao'].fillna(0).astype('int64')
df['ano_datEmissao'] = df['ano_datEmissao'].fillna(0).astype('int64')

In [21]:
# Verificando se os tipos de dados das colunas criadas foram convertidos corretamente
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207575 entries, 0 to 207574
Data columns (total 35 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   txNomeParlamentar          207575 non-null  string
 1   cpf                        207575 non-null  string
 2   ideCadastro                207575 non-null  string
 3   nuCarteiraParlamentar      207575 non-null  string
 4   nuLegislatura              207575 non-null  int64
 5   sgUF                       206639 non-null  string
 6   sgPartido                  206639 non-null  string
 7   codLegislatura             207575 non-null  string
 8   numSubCota                 207575 non-null  string
 9   txtDescricao               207575 non-null  string
 10  numEspecificacaoSubCota    207575 non-null  string
 11  txtDescricaoEspecificacao  71467 non-null   string
 12  txtFornecedor              207575 non-null  string
 13  txtCNPJCPF                 170996 non-null  string
 14  txtNumero                  207575 non-null  string
 15  indTipoDocumento           207575 non-null  string
 16  datEmissao                 199741 non-null  datetime64[ns]
 17  vlrDocumento               207575 non-null  float64
 18  vlrGlosa                   207575 non-null  float64
 19  vlrLiquido                 207575 non-null  float64
 20  numMes                     207575 non-null  int64
 21  numAno                     207575 non-null  int64
 22  numParcela                 207575 non-null  int64
 23  txtPassageiro              37225 non-null   string
 24  txtTrecho                  37124 non-null   string
 25  numLote                    207575 non-null  string
 26  numRessarcimento           207575 non-null  string
 27  datPagamentoRestituicao    31 non-null      datetime64[ns]
 28  vlrRestituicao             31 non-null      float64
 29  nuDeputadoId               207575 non-null  string
 30  ideDocumento               207575 non-null  string
 31  urlDocumento               157170 non-null  string
 32  dia_datEmissao             207575 non-null  int64
 33  mes_datEmissao             207575 non-null  int64
 34  ano_datEmissao             207575 non-null  int64
dtypes: datetime64[ns](2), float64(4), int64(7), string(22)
memory usage: 55.4 MB

In [22]:
# Verificando os 3 últimos registros do dataframe
df.tail(3)

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento,dia_datEmissao,mes_datEmissao,ano_datEmissao
207572,Vanderlan Alves,2964896380,234673,632,2023,CE,REPUBLICANOS,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,<NA>,EM LOCACAO E COMERCIO DE VEICULOS LTDA,545.802.440/0020-9,18,4,2025-12-22,10400.0,0.0,10400.0,12,2025,0,<NA>,<NA>,2199423,0,NaT,NaN,3803,8033995,https://www.camara.leg.br/cota-parlamentar/not...,22,12,2025
207573,Heloísa Helena,36450316420,234788,633,2023,RJ,REDE,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,EDVALDO FRANCISCO DE OLIVEIRA 49191160120,323.738.120/0017-9,257,4,2025-12-19,194.4,0.0,194.4,12,2025,0,<NA>,<NA>,2206738,0,NaT,NaN,3804,8046527,https://www.camara.leg.br/cota-parlamentar/not...,19,12,2025
207574,Heloísa Helena,36450316420,234788,633,2023,RJ,REDE,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,MIL E UMA IDEIAS CONSULTORIA EM MARKETING E CO...,366.781.610/0018-6,188,0,2026-02-02,15000.0,0.0,15000.0,12,2025,0,<NA>,<NA>,2205674,0,NaT,NaN,3804,8044458,https://www.camara.leg.br/cota-parlamentar/doc...,2,2,2026

In [23]:
# Verificando exemplos de registros na coluna 'datPagamentoRestituicao' que não sejam NaN
datPagamentoRestituicao_nao_nulos = df[df['datPagamentoRestituicao'].notna()]
datPagamentoRestituicao_nao_nulos

,txNomeParlamentar,cpf,ideCadastro,nuCarteiraParlamentar,nuLegislatura,sgUF,sgPartido,codLegislatura,numSubCota,txtDescricao,numEspecificacaoSubCota,txtDescricaoEspecificacao,txtFornecedor,txtCNPJCPF,txtNumero,indTipoDocumento,datEmissao,vlrDocumento,vlrGlosa,vlrLiquido,numMes,numAno,numParcela,txtPassageiro,txtTrecho,numLote,numRessarcimento,datPagamentoRestituicao,vlrRestituicao,nuDeputadoId,ideDocumento,urlDocumento,dia_datEmissao,mes_datEmissao,ano_datEmissao
2812,Arlindo Chinaglia,6821146187,73433,336,2023,SP,PT,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO GRANDPRIX DE INTERLAGOS LTDA,169.299.630/0010-4,019314,1,2025-04-06 00:00:00,170.23,0.00,0.0,4,2025,0,<NA>,<NA>,2129268,0,2025-05-07,170.23,974,7901620,https://www.camara.leg.br/cota-parlamentar/doc...,6,4,2025
3053,Arlindo Chinaglia,6821146187,73433,336,2023,SP,PT,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,COOPERATIVA MISTA DE TRABALHO DOS MOTORISTAS A...,465.539.470/0012-0,849477774,1,2025-03-26 00:00:00,77.00,0.00,0.0,3,2025,0,<NA>,<NA>,2129272,0,2025-05-07,77.00,974,7903171,https://www.camara.leg.br/cota-parlamentar/doc...,26,3,2025
7174,Luiz Carlos Hauly,8682607972,73778,549,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,",auricio teixeira barbosa",269.698.068/39 -,sn,1,2025-06-27 00:00:00,36.60,0.00,0.0,6,2025,0,<NA>,<NA>,2148960,0,2025-07-09,36.60,824,7938485,https://www.camara.leg.br/cota-parlamentar/doc...,27,6,2025
7176,Luiz Carlos Hauly,8682607972,73778,549,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,ANDRE DOS SANTOS,298.603.538/83 -,sn,1,2025-06-19 00:00:00,70.00,0.00,0.0,6,2025,0,<NA>,<NA>,2148960,0,2025-07-09,70.00,824,7938471,https://www.camara.leg.br/cota-parlamentar/doc...,19,6,2025
7187,Luiz Carlos Hauly,8682607972,73778,549,2023,PR,PODE,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,MILOSO E MILOZO LTDA,107.701.940/0016-8,000000000620,1,2025-06-02 00:00:00,660.00,0.00,0.0,5,2025,0,<NA>,<NA>,2144384,0,2025-06-16,660.00,824,7929746,https://www.camara.leg.br/cota-parlamentar/doc...,2,6,2025
23727,Laura Carneiro,79401546720,74856,307,2023,RJ,PSD,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,<NA>,SERV RIO TERCEIRIZAÇÃO E SERVIÇOS,104.798.610/0015-8,001829,1,2025-06-30 00:00:00,4200.00,0.00,0.0,6,2025,0,<NA>,<NA>,2150640,0,2025-07-08,4200.00,1118,7941710,https://www.camara.leg.br/cota-parlamentar/doc...,30,6,2025
28695,Ana Paula Leão,52030849634,107970,222,2023,MG,PP,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,Facebook Serviços Online do Brasil Ltda.,133.470.160/0011-7,125511406,0,2025-12-03 00:00:00,979.32,0.00,0.0,11,2025,0,<NA>,<NA>,2198113,0,2026-01-26,979.32,3664,8031374,https://www.camara.leg.br/cota-parlamentar/doc...,3,12,2025
30579,Átila Lira,74568701368,123086,109,2023,PI,PP,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,GOMO COMUNICAÇÂO LTDA,518.126.010/0013-0,119,0,2026-01-22 00:00:00,2000.00,0.00,0.0,12,2025,0,<NA>,<NA>,2204693,0,2026-02-26,214.42,3670,8043013,https://www.camara.leg.br/cota-parlamentar/doc...,22,1,2026
69845,Afonso Motta,10777296004,178835,490,2023,RS,PDT,57,120,LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES,0,<NA>,ELF Locadora de Veículos Ltda,074.474.050/0011-1,25985,1,2025-09-02 00:00:00,4900.00,0.00,0.0,8,2025,0,<NA>,<NA>,2169554,0,2025-09-18,4900.00,2880,7976889,https://www.camara.leg.br/cota-parlamentar/doc...,2,9,2025
72864,Evair Vieira de Melo,2261265794,178871,274,2023,ES,PP,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,UBER DO BRASIL TECNOLOGIA LTDA.,178.956.460/0018-7,16.1,1,2025-10-16 00:00:00,40.86,0.00,0.0,10,2025,0,<NA>,<NA>,2183477,0,2025-12-12,40.86,2984,8003831,https://www.camara.leg.br/cota-parlamentar/doc...,16,10,2025
72866,Evair Vieira de Melo,2261265794,178871,274,2023,ES,PP,57,122,"SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO",0,<NA>,UBER DO BRASIL TECNOLOGIA LTDA.,178.956.460/0018-7,16.2,1,2025-10-16 00:00:00,51.82,0.00,0.0,10,2025,0,<NA>,<NA>,2183477,0,2025-12-12,51.82,2984,8003834,https://www.camara.leg.br/cota-parlamentar/doc...,16,10,2025
84117,Miguel Lombardi,5209979806,178985,378,2023,SP,PL,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,RODOPOSTO BANDEIRANTES NORTE LTDA,052.898.510/0011-0,307013,0,2025-06-29 00:00:00,161.12,0.00,0.0,6,2025,0,<NA>,<NA>,2149839,0,2025-07-24,161.12,2995,7939265,https://www.camara.leg.br/cota-parlamentar/doc...,29,6,2025
108663,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,141992,0,2025-07-29 00:00:00,1625.40,0.00,0.0,7,2025,0,<NA>,<NA>,2165519,0,2025-10-21,1625.40,3344,7969334,https://www.camara.leg.br/cota-parlamentar/doc...,29,7,2025
108665,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,142321,0,2025-08-06 00:00:00,15784.40,0.00,0.0,7,2025,0,<NA>,<NA>,2163132,0,2025-10-21,15784.41,3344,7965631,https://www.camara.leg.br/cota-parlamentar/doc...,6,8,2025
108667,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,142322,0,2025-08-06 00:00:00,1344.33,0.00,0.0,7,2025,0,<NA>,<NA>,2164214,0,2025-10-21,1344.33,3344,7966850,https://www.camara.leg.br/cota-parlamentar/doc...,6,8,2025
108669,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,142434,0,2025-08-08 00:00:00,3203.56,0.00,0.0,8,2025,0,<NA>,<NA>,2163141,0,2025-10-21,3203.56,3344,7965673,https://www.camara.leg.br/cota-parlamentar/doc...,8,8,2025
108671,Helio Lopes,891743723,204444,303,2023,RJ,PL,57,14,"HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO ...",0,<NA>,IBIS SOROCABA,024.197.650/0205-9,142614,0,2025-08-14 00:00:00,2055.42,0.00,0.0,8,2025,0,<NA>,<NA>,2164173,0,2025-10-21,2055.42,3344,7965679,https://www.camara.leg.br/cota-parlamentar/doc...,14,8,2025
112498,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,1,4,2025-05-01 00:00:00,245.35,0.00,0.0,5,2025,0,<NA>,<NA>,2131548,0,2025-09-22,245.35,3391,7907582,https://www.camara.leg.br/cota-parlamentar/not...,1,5,2025
112500,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,10147,4,2025-09-06 00:00:00,449.28,0.00,0.0,9,2025,0,<NA>,<NA>,2170221,0,2025-09-22,449.28,3391,7978270,https://www.camara.leg.br/cota-parlamentar/not...,6,9,2025
112502,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,24,4,2025-05-03 00:00:00,224.68,0.00,0.0,5,2025,0,<NA>,<NA>,2131548,0,2025-09-22,224.68,3391,7907577,https://www.camara.leg.br/cota-parlamentar/not...,3,5,2025
112504,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,270,4,2025-05-17 00:00:00,226.12,0.00,0.0,5,2025,0,<NA>,<NA>,2136590,0,2025-09-22,226.12,3391,7916735,https://www.camara.leg.br/cota-parlamentar/not...,17,5,2025
112506,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,3724,4,2025-07-18 00:00:00,424.53,0.00,0.0,7,2025,0,<NA>,<NA>,2155369,0,2025-09-22,424.53,3391,7950646,https://www.camara.leg.br/cota-parlamentar/not...,18,7,2025
112508,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,41,4,2025-05-05 10:26:02,299.98,0.00,0.0,5,2025,0,<NA>,<NA>,2131548,0,2025-09-22,299.98,3391,7907572,https://www.camara.leg.br/cota-parlamentar/not...,5,5,2025
112510,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,559,4,2025-05-24 00:00:00,242.61,0.00,0.0,5,2025,0,<NA>,<NA>,2138363,0,2025-09-22,242.61,3391,7920174,https://www.camara.leg.br/cota-parlamentar/not...,24,5,2025
112512,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,6062,4,2025-08-08 16:10:20,260.94,0.00,0.0,8,2025,0,<NA>,<NA>,2160985,0,2025-09-22,260.94,3391,7961248,https://www.camara.leg.br/cota-parlamentar/not...,8,8,2025
112514,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,81,4,2025-05-08 15:48:58,350.00,0.00,0.0,5,2025,0,<NA>,<NA>,2134218,0,2025-09-22,350.00,3391,7912443,https://www.camara.leg.br/cota-parlamentar/not...,8,5,2025
112516,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,8624,4,2025-08-31 00:00:00,388.17,0.00,0.0,8,2025,0,<NA>,<NA>,2167873,0,2025-09-22,388.17,3391,7973703,https://www.camara.leg.br/cota-parlamentar/not...,31,8,2025
112518,Juninho do Pneu,7845799700,204457,308,2023,RJ,UNIÃO,57,3,COMBUSTÍVEIS E LUBRIFICANTES.,1,Veículos Automotores,AUTO POSTO PARADA E DESCANSO LTDA,576.053.010/0016-6,895,4,2025-05-26 00:00:00,329.87,0.00,0.0,5,2025,0,<NA>,<NA>,2138363,0,2025-09-22,329.87,3391,7920177,https://www.camara.leg.br/cota-parlamentar/not...,26,5,2025
136974,Gilvan da Federal,8449011728,220526,281,2023,ES,PL,57,5,DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.,0,<NA>,J WESLWY DE S PEREIRA,533.241.400/0018-1,00012,0,2025-05-02 00:00:00,7000.00,0.00,0.0,5,2025,0,<NA>,<NA>,2131904,0,2025-06-09,5870.97,3650,7908240,https://www.camara.leg.br/cota-parlamentar/doc...,2,5,2025
196068,Carol Dartora,4310202993,220704,444,2023,PR,PT,57,1,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,0,<NA>,SANEPAR,764.840.130/0014-5,270,1,2025-05-27 00:00:00,176.34,6.08,0.0,5,2025,0,<NA>,<NA>,2145810,0,2025-07-09,170.26,3632,7932439,https://www.camara.leg.br/cota-parlamentar/doc...,27,5,2025
203055,Saulo Pedroso,30420230874,226837,559,2023,SP,PSD,57,13,FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR,0,<NA>,VA DOS SANTOS RESTAURANTE E LACHONETE,349.788.620/0010-5,000477,0,2025-05-05 00:00:00,200.00,0.00,0.0,5,2025,0,<NA>,<NA>,2132641,0,2025-05-21,200.00,3748,7909605,https://www.camara.leg.br/cota-parlamentar/doc...,5,5,2025

## Load

In [24]:


# Criando a engine do SQlAlchemy
engine = sqlalchemy.create_engine('sqlite:///banco_de_dados_do_desafio.db')

In [25]:
# Verificando tamanho máximo de caracteres na colunas do tipo string
print(max(map(len, df['cpf'])))
print(max(map(len, df['ideCadastro'])))
print(max(map(len, df['nuCarteiraParlamentar'])))
print(max(map(len, df['codLegislatura'])))
print(max(map(len, df['numSubCota'])))
print(max(map(len, df['numEspecificacaoSubCota'])))
print(max(map(len, df['txtCNPJCPF'].fillna('')))) # Modificando valores nulos com um string vazia antes de dar o print do len()
print(max(map(len, df['txtNumero'])))
print(max(map(len, df['indTipoDocumento'])))
print(max(map(len, df['numLote'])))
print(max(map(len, df['numRessarcimento'])))
print(max(map(len, df['nuDeputadoId'])))
print(max(map(len, df['ideDocumento'])))
print(max(map(len, df['sgPartido'].fillna('')))) # Modificando valores nulos com um string vazia antes de dar o print do len()
print(max(map(len, df['txtDescricao'])))
print(max(map(len, df['txtDescricaoEspecificacao'].fillna('')))) # Modificando valores nulos com um string vazia antes de dar o print do len()
print(max(map(len, df['txtFornecedor'])))
print(max(map(len, df['txtPassageiro'].fillna(''))))
print(max(map(len, df['txtTrecho'].fillna(''))))
print(max(map(len, df['urlDocumento'].fillna(''))))

11
6
3
2
3
1
19
30
1
7
1
4
7
13
57
20
95
71
32
92

### Inserir dados no banco SQL

In [26]:
# Query para criar tabela
query_criar_tabela = """
CREATE TABLE IF NOT EXISTS despesas_pela_cota_para_exercicio_da_atividade_parlamentar (
    txNomeParlamentar VARCHAR(100),
    cpf VARCHAR(11),
    ideCadastro VARCHAR(6),
    nuCarteiraParlamentar VARCHAR(3),
    nuLegislatura INT(4),
    sgUF VARCHAR(2),
    sgPartido VARCHAR(25),
    codLegislatura VARCHAR(2),
    numSubCota VARCHAR(3),
    txtDescricao VARCHAR(120),
    numEspecificacaoSubCota VARCHAR(1),
    txtDescricaoEspecificacao VARCHAR(50),
    txtFornecedor VARCHAR(300),
    txtCNPJCPF VARCHAR(19),
    txtNumero VARCHAR(50),
    indTipoDocumento VARCHAR(1),
    datEmissao DATE,
    vlrDocumento FLOAT,
    vlrGlosa FLOAT,
    vlrLiquido FLOAT,
    numMes INT(2),
    numAno INT(4),
    numParcela INT(3),
    txtPassageiro VARCHAR(150),
    txtTrecho VARCHAR(60),
    numLote VARCHAR(15),
    numRessarcimento VARCHAR(1),
    datPagamentoRestituicao DATE,
    vlrRestituicao FLOAT,
    nuDeputadoId VARCHAR(10),
    ideDocumento VARCHAR(15),
    urlDocumento VARCHAR(250),
    dia_datEmissao INT(2),
    mes_datEmissao INT(2),
    ano_datEmissao INT(4)
)
"""

In [27]:
# Executando a query de criação da tabela
try:
    engine.raw_connection().cursor().execute(query_criar_tabela)
except:
    print("Essa tabela já existe. ")

In [28]:
# Query para inserir os dados na tabela criada
query_insercao_dados = """
INSERT INTO despesas_pela_cota_para_exercicio_da_atividade_parlamentar (
    txNomeParlamentar,
    cpf,
    ideCadastro,
    nuCarteiraParlamentar,
    nuLegislatura,
    sgUF,
    sgPartido,
    codLegislatura,
    numSubCota,
    txtDescricao,
    numEspecificacaoSubCota,
    txtDescricaoEspecificacao,
    txtFornecedor,
    txtCNPJCPF,
    txtNumero,
    indTipoDocumento,
    datEmissao,
    vlrDocumento,
    vlrGlosa,
    vlrLiquido,
    numMes,
    numAno,
    numParcela,
    txtPassageiro,
    txtTrecho,
    numLote,
    numRessarcimento,
    datPagamentoRestituicao,
    vlrRestituicao,
    nuDeputadoId,
    ideDocumento,
    urlDocumento,
    dia_datEmissao,
    mes_datEmissao,
    ano_datEmissao
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
"""

# Inserindo os dados da origem (df) dentro da tabela no banco de dados do SQLAlchemy
registros_inseridos = df.tail(100).to_sql( # Inserindo os últimos 100 registros do dataframe
    'despesas_pela_cota_para_exercicio_da_atividade_parlamentar',
    engine,
    if_exists = 'append', # Se a tabela existir, serão inseridos os dados nela
    index = False, # Para não salvar o índice do dataframe Pandas como uma coluna no banco de dados
    method = 'multi' # Para passar múltiplos valores em uma única inserção de dados
    )

try:
    if registros_inseridos:
        print(f"Os dados de {registros_inseridos} registros foram inseridos com sucesso no banco de dados SQLAlchemy. ")
    else:
        print("Houve erro ao inserir os dados no banco de dados SQLAlchemy. ")
except:
    print(ValueError)

Os dados de 100 registros foram inseridos com sucesso no banco de dados SQLAlchemy.

### Deletar tabela

In [ ]:
# Deletando a tabela criada
query_deletar_tabela = "DROP TABLE despesas_pela_cota_para_exercicio_da_atividade_parlamentar"

engine.raw_connection().cursor().execute(query_deletar_tabela)